"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Activity, ClipboardList, LayoutDashboard, LogIn, LogOut, Package, Search, ShieldCheck, ShoppingCart, Users, X } from "lucide-react";

type Medicine = { id: number; name: string; batch: string; stock: number; threshold: number; recalled: boolean };
type Patient = { id: number; name: string; phone: string; threshold: number };
const seededMedicines: Medicine[] = [
  { id: 1, name: "Paracetamol", batch: "BATCH-1000", stock: 12, threshold: 5, recalled: false }, { id: 2, name: "Amoxicillin", batch: "BATCH-1001", stock: 6, threshold: 7, recalled: false }, { id: 3, name: "Ibuprofen", batch: "BATCH-1002", stock: 28, threshold: 4, recalled: false }, { id: 4, name: "Cetirizine", batch: "BATCH-1003", stock: 4, threshold: 6, recalled: false }, { id: 5, name: "Metformin", batch: "BATCH-1004", stock: 41, threshold: 3, recalled: false }, { id: 6, name: "Amlodipine", batch: "BATCH-1005", stock: 9, threshold: 7, recalled: false }, { id: 7, name: "Omeprazole", batch: "BATCH-1006", stock: 17, threshold: 5, recalled: false }, { id: 8, name: "Losartan", batch: "BATCH-1007", stock: 3, threshold: 6, recalled: false }, { id: 9, name: "Azithromycin", batch: "BATCH-1008", stock: 22, threshold: 4, recalled: true }, { id: 10, name: "Aspirin", batch: "BATCH-1009", stock: 34, threshold: 5, recalled: false },
];
const seededPatients: Patient[] = [{ id: 1, name: "Michael Brown", phone: "9876543210", threshold: 4 }, { id: 2, name: "Sarah Davis", phone: "9876543211", threshold: 6 }, { id: 3, name: "David Miller", phone: "9876543212", threshold: 3 }, { id: 4, name: "Emma Wilson", phone: "9876543213", threshold: 7 }, { id: 5, name: "James Taylor", phone: "9876543214", threshold: 5 }];
const nav = [{ href: "/", label: "Overview", icon: LayoutDashboard }, { href: "/inventory", label: "Inventory", icon: Package }, { href: "/patients", label: "Patients", icon: Users }, { href: "/checkout", label: "Secure checkout", icon: ShoppingCart }, { href: "/audit", label: "Audit logs", icon: ClipboardList }];

export default function MediVaultDashboard({ section = "overview" }: { section?: string }) {
  const pathname = usePathname(); const [admin, setAdmin] = useState(false); const [loginOpen, setLoginOpen] = useState(false); const [credentials, setCredentials] = useState({ username: "", password: "" }); const [error, setError] = useState("");
  useEffect(() => setAdmin(sessionStorage.getItem("medivault-admin") === "true"), []);
  function login(event: FormEvent) { event.preventDefault(); if (credentials.username === "admin" && credentials.password === "admin") { sessionStorage.setItem("medivault-admin", "true"); window.location.reload(); } else setError("Invalid administrator credentials."); }
  function logout() { sessionStorage.removeItem("medivault-admin"); window.location.href = "/"; }
  if (!admin) return <PublicPortal open={loginOpen} credentials={credentials} setCredentials={setCredentials} error={error} onOpen={() => { setError(""); setCredentials({ username: "", password: "" }); setLoginOpen(true); }} onClose={() => setLoginOpen(false)} onSubmit={login} />;
  const title = section === "overview" ? "Operations overview" : section === "checkout" ? "Secure checkout" : section === "audit" ? "Audit logs" : section[0].toUpperCase() + section.slice(1);
  return <div className="app-shell"><aside className="sidebar"><Brand /><div className="role"><ShieldCheck size={16} /> Administrator</div><nav aria-label="Admin navigation">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={pathname === href ? "active" : ""}><Icon size={17} />{label}</Link>)}</nav><div className="sidebar-bottom"><div className="status"><span />Local data connected</div><button onClick={logout}><LogOut size={16} />Sign out</button></div></aside><main className="main"><header><div><p className="eyebrow">MEDIVAULT / {section.toUpperCase()}</p><h1>{title}</h1></div><button className="admin-button" onClick={logout}><span className="avatar">AD</span>Administrator</button></header>{section === "overview" ? <Overview /> : <Section section={section} />}</main></div>;
}
function Brand() { return <Link href="/" className="brand"><img src="/medivault-logo.png" alt="MediVault logo" /><span>Medi<span>Vault</span></span></Link>; }
function PublicPortal({ open, credentials, setCredentials, error, onOpen, onClose, onSubmit }: any) { return <main className="public-shell"><header className="public-header"><Brand /><nav><Link href="#find">Find a pharmacy</Link><Link href="#medicines">Medicine availability</Link><button className="admin-button" onClick={onOpen}><LogIn size={16} />Admin Login</button></nav></header><section className="public-hero"><p className="eyebrow">TRUSTED CARE, CLOSE TO HOME</p><h1>Find what you need.<br /><em>When you need it.</em></h1><p>Check verified medicine availability in a privacy-first local pharmacy network.</p><div className="public-search" id="find"><Search size={18} /><input aria-label="Search medical shops" placeholder="Search by medicine, shop, or location" /><button className="primary">Search network</button></div></section><section className="shop-grid" id="medicines"><div className="section-heading"><div><p className="eyebrow">VERIFIED NETWORK</p><h2>Medical shops near you</h2></div><span className="live-pill"><Activity size={14} /> Local inventory</span></div>{["Northstar Pharmacy", "Civic Health Mart", "Greenline Medicals"].map((shop, i) => <article className="shop-card" key={shop}><div className="shop-icon">{i + 1}</div><div><h3>{shop}</h3><p>{i + 1}.2 miles away · Open until 9 PM</p><span className="badge healthy">Inventory verified</span></div><Link href="/inventory">View stock →</Link></article>)}</section>{open && <div className="modal-backdrop"><form className="login-modal" onSubmit={onSubmit}><button type="button" className="modal-close" onClick={onClose} aria-label="Close"><X size={17} /></button><p className="eyebrow">SECURE ACCESS</p><h2>Admin Login</h2><p className="muted">Enter the administrator credentials to access local records.</p><label>Username<input required autoComplete="username" value={credentials.username} onChange={(e) => setCredentials({ ...credentials, username: e.target.value })} /></label><label>Password<input required type="password" autoComplete="current-password" value={credentials.password} onChange={(e) => setCredentials({ ...credentials, password: e.target.value })} /></label>{error && <p className="form-error">{error}</p>}<button className="primary" type="submit">Enter admin mode</button></form></div>}</main>; }
function Overview() { const low = seededMedicines.filter((m) => !m.recalled && m.stock <= m.threshold); const recalled = seededMedicines.filter((m) => m.recalled); return <><div className="hero"><div><p className="eyebrow">LIVE MONITORING</p><h2>Welcome, Administrator.</h2><p>Your local pharmacy data is ready. Here&apos;s the current operational snapshot.</p></div><Link href="/checkout" className="primary"><ShoppingCart size={17} />Open secure checkout</Link></div><div className="stats"><Link href="/inventory?filter=low"><span>LOW STOCK ALERTS</span><strong>{low.length}</strong><small>Stock at or below threshold →</small></Link><Link href="/patients"><span>REGISTERED PATIENTS</span><strong>{seededPatients.length}</strong><small>Local records →</small></Link><Link href="/inventory"><span>TOTAL MEDICINES</span><strong>{seededMedicines.length}</strong><small>Seeded records →</small></Link><Link href="/inventory?filter=recalled"><span>RECALLED BATCHES</span><strong>{recalled.length}</strong><small>Quarantined →</small></Link></div><section className="panel"><div className="panel-head"><div><p className="eyebrow">INVENTORY CONTROL</p><h3>Stock requiring attention</h3></div><Link href="/inventory?filter=low">View filtered inventory →</Link></div><Table medicines={seededMedicines.filter((m) => m.recalled || (!m.recalled && m.stock <= m.threshold))} /></section></>; }
function Table({ medicines }: { medicines: Medicine[] }) { return <div className="table-wrap"><table><thead><tr><th>Medicine</th><th>Batch</th><th>Stock / threshold</th><th>Status</th></tr></thead><tbody>{medicines.map((m) => <tr key={m.id}><td><b>{m.name}</b></td><td className="muted">{m.batch}</td><td>{m.stock} / {m.threshold} min</td><td><span className={`badge ${m.recalled ? "recalled" : "warning"}`}>{m.recalled ? "Recalled" : "Low stock"}</span></td></tr>)}</tbody></table></div>; }
function Section({ section }: { section: string }) { const [medicines, setMedicines] = useState(seededMedicines); const [patients, setPatients] = useState(seededPatients); const [modal, setModal] = useState<"medicine" | "patient" | null>(null); const low = medicines.filter((m) => !m.recalled && m.stock <= m.threshold); const filter = typeof window !== "undefined" ? new URLSearchParams(window.location.search).get("filter") : null;
  if (section === "inventory") return <section className="panel full"><div className="panel-head"><div><p className="eyebrow">MEDIVAULT / INVENTORY</p><h2>Inventory control</h2><p className="muted">{medicines.length} medicines · {low.length} low stock · {medicines.filter((m) => m.recalled).length} recalled</p></div><button className="primary" onClick={() => setModal("medicine")}>+ Add Medicine</button></div><Table medicines={filter === "low" ? low : filter === "recalled" ? medicines.filter((m) => m.recalled) : medicines} /><AddMedicine open={modal === "medicine"} close={() => setModal(null)} add={(m: Medicine) => { setMedicines([...medicines, m]); setModal(null); }} /></section>;
  if (section === "patients") return <section className="panel full"><div className="panel-head"><div><p className="eyebrow">MEDIVAULT / PATIENTS</p><h2>Patient registry</h2><p className="muted">{patients.length} registered local patients</p></div><button className="primary" onClick={() => setModal("patient")}>+ Register Patient</button></div><div className="patient-list">{patients.map((p) => <div className="patient-row" key={p.id}><span className="avatar">{String(p.id).padStart(2, "0")}</span><div><b>{p.name}</b><small>{p.phone} · Warning threshold: {p.threshold}</small></div><span className="badge healthy">Active</span></div>)}</div><AddPatient open={modal === "patient"} close={() => setModal(null)} add={(p: Patient) => { setPatients([...patients, p]); setModal(null); }} /></section>;
  if (section === "checkout") return <section className="panel checkout"><p className="eyebrow">SECURE POS TERMINAL</p><h2>Process a prescription safely.</h2><p className="muted">Validate patient thresholds, stock limits, and recalled batches before dispensing.</p><label>Search patient or prescription<input placeholder="Search by patient ID or medicine name" /></label><button className="primary">Begin secure checkout</button></section>;
  return <section className="panel full"><p className="eyebrow">MEDIVAULT / AUDIT</p><h2>System audit trail</h2>{["Inventory records loaded", "Patient registry accessed", "Secure checkout ready"].map((x) => <div className="activity-row" key={x}><span className="activity-dot" /><b>{x}</b><small>Current session</small></div>)}</section>;
}
function AddMedicine({ open, close, add }: any) { const [form, setForm] = useState({ name: "", batch: "", stock: "", recalled: false }); if (!open) return null; return <Modal title="Add Medicine" close={close}><form onSubmit={(e) => { e.preventDefault(); add({ id: Date.now(), name: form.name, batch: form.batch, stock: Number(form.stock), threshold: 5, recalled: form.recalled }); }}><label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Batch Number<input required value={form.batch} onChange={(e) => setForm({ ...form, batch: e.target.value })} /></label><label>Stock Quantity<input required min="0" type="number" value={form.stock} onChange={(e) => setForm({ ...form, stock: e.target.value })} /></label><label className="check"><input type="checkbox" checked={form.recalled} onChange={(e) => setForm({ ...form, recalled: e.target.checked })} /> Is Recalled</label><button className="primary" type="submit">Add to inventory</button></form></Modal>; }
function AddPatient({ open, close, add }: any) { const [form, setForm] = useState({ name: "", phone: "", threshold: "" }); if (!open) return null; return <Modal title="Register Patient" close={close}><form onSubmit={(e) => { e.preventDefault(); add({ id: Date.now(), name: form.name, phone: form.phone, threshold: Number(form.threshold) }); }}><label>Patient Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Phone Number<input required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label>Warning Threshold<input required min="1" type="number" value={form.threshold} onChange={(e) => setForm({ ...form, threshold: e.target.value })} /></label><button className="primary" type="submit">Register patient</button></form></Modal>; }
function Modal({ title, close, children }: any) { return <div className="modal-backdrop"><div className="login-modal"><button className="modal-close" onClick={close} aria-label="Close"><X size={17} /></button><p className="eyebrow">MEDIVAULT RECORDS</p><h2>{title}</h2>{children}</div></div>; }
